import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/layout/Navbar'

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <section className="p-4">
          Hello, world!
        </section>
      </main>
    </div>
  )
}

export default Home
