import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import SearchBar from '../components/SearchBar'
import JobTypes from '../components/JobTypes'
import Departments from '../components/Departments'
import WorkSchedules from '../components/WorkSchedules'
import Experiences from '../components/Experiences'
import JobBoard from '../components/JobBoard'

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar />
        <div className="container mx-auto">
          <div className="w-full pt-28">
            <section className="flex item-center mt-2 mb-2 mx-2 bg-white">
              <SearchBar/>
            </section>
            <section className="mt-4 mx-2 flex">
              <div className="w-64 hidden lg:block">
                <div className="w-full h-full">
                  <JobTypes/>
                  <Departments/>
                  <WorkSchedules/>
                  <Experiences/>
                </div>
              </div>
              <JobBoard/>
            </section>
          </div>
        </div>
        <Footer/>
      </main>
    </div>
  )
}

export default Home
